#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
/* automatically generated by rust-bindgen 0.55.1 */

extern "C" {
    pub fn td_json_client_create() -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn td_json_client_send(
        client: *mut ::std::os::raw::c_void,
        request: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn td_json_client_receive(
        client: *mut ::std::os::raw::c_void,
        timeout: f64,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn td_json_client_execute(
        client: *mut ::std::os::raw::c_void,
        request: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn td_json_client_destroy(client: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn td_set_log_file_path(file_path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn td_set_log_max_file_size(max_file_size: ::std::os::raw::c_longlong);
}
extern "C" {
    pub fn td_set_log_verbosity_level(new_verbosity_level: ::std::os::raw::c_int);
}
pub type td_log_fatal_error_callback_ptr =
    ::std::option::Option<unsafe extern "C" fn(error_message: *const ::std::os::raw::c_char)>;
extern "C" {
    pub fn td_set_log_fatal_error_callback(callback: td_log_fatal_error_callback_ptr);
}
